/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lucaslpmoura_JNI_Blackjack_CBlackjack */

#ifndef _Included_com_lucaslpmoura_JNI_Blackjack_CBlackjack
#define _Included_com_lucaslpmoura_JNI_Blackjack_CBlackjack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lucaslpmoura_JNI_Blackjack_CBlackjack
 * Method:    initializeGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lucaslpmoura_JNI_1Blackjack_CBlackjack_initializeGame
  (JNIEnv *, jobject);

/*
 * Class:     com_lucaslpmoura_JNI_Blackjack_CBlackjack
 * Method:    processAction
 * Signature: (Lcom/lucaslpmoura/JNI_Blackjack/CBlackjack/Deck;Lcom/lucaslpmoura/JNI_Blackjack/CBlackjack/Player;Lcom/lucaslpmoura/JNI_Blackjack/CBlackjack/Player;Lcom/lucaslpmoura/JNI_Blackjack/CBlackjack/Action;)Lcom/lucaslpmoura/JNI_Blackjack/CBlackjack/GameState;
 */
JNIEXPORT jobject JNICALL Java_com_lucaslpmoura_JNI_1Blackjack_CBlackjack_processAction
  (JNIEnv *, jobject);

/*
 * Class:     com_lucaslpmoura_JNI_Blackjack_CBlackjack
 * Method:    calculateHandScore
 * Signature: (Lcom/lucaslpmoura/JNI_Blackjack/CBlackjack/Hand;)I
 */
JNIEXPORT jint JNICALL Java_com_lucaslpmoura_JNI_1Blackjack_CBlackjack_calculateHandScore
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_lucaslpmoura_JNI_Blackjack_CBlackjack
 * Method:    freeStructs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lucaslpmoura_JNI_1Blackjack_CBlackjack_freeStructs
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
